<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VVM8OTS" ignored="0" name="Test" tests="8" failures="2" timestamp="03 Oct 2019 05:00:06 GMT" time="0.089" errors="0">
  <testcase name="retry1" time="0.015" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase name="retry1" time="0.003" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase name="retry1" time="0.002" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry1 -->
  <testcase name="retry1" time="0.001" classname="retryanalyzer.retrylogic.retrylogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at retryanalyzer.retrylogic.retrylogic.retry1(retrylogic.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- retry1 -->
  <testcase name="retry2" time="0.002" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry2 -->
  <testcase name="retry2" time="0.002" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry2 -->
  <testcase name="retry2" time="0.002" classname="retryanalyzer.retrylogic.retrylogic">
    <skipped/>
  </testcase> <!-- retry2 -->
  <testcase name="retry2" time="0.002" classname="retryanalyzer.retrylogic.retrylogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at retryanalyzer.retrylogic.retrylogic.retry2(retrylogic.java:13)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- retry2 -->
</testsuite> <!-- Test -->
